version: "3"
networks: 
  hub: 
    driver: bridge
services: 
  app: 
    build: 
      context: "."
    container_name: app
    depends_on: 
      - seleniumhub
      - firefoxnode
      - chromenode
    networks: 
      - hub
    volumes: 
      - "$PWD/reports:/root/automationFramework/reports:rw"
  chromenode: 
    container_name: chrome_node
    depends_on: 
      - seleniumhub
    environment: 
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    image: selenium/node-chrome
    networks: 
      - hub
  firefoxnode: 
    container_name: firefox_node
    depends_on: 
      - seleniumhub
    environment: 
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    image: selenium/node-firefox
    networks: 
      - hub
  seleniumhub: 
    container_name: selenium-hub
    image: selenium/hub
    networks: 
      - hub
    ports: 
      - "4444:4444"
